eureka:
  client:
    enabled: false
    fetch-registry: true
    register-with-eureka: false
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: kenny
    url: jdbc:mysql://127.0.0.1:3306/dp_demo?serverTimezone=GMT%2B8

  #    driver-class-name: org.h2.Driver
#    username: root
#    password: root
#    url: 'jdbc:h2:mem:test'
#    schema: 'classpath:db/sql/demo_schema.sql'
#    data: 'classpath:db/sql/demo_data.sql'
#  h2:
#    console:
#      enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: 127.0.0.1
    port: '6379'

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
